# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          FINNHUB: ${{ secrets.FINNHUB }}

  versioning:
    needs: build
    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    outputs:
      version: ${{ steps.latest_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      
      - name: Git Identity
        run: |
          git checkout main
          git fetch --all --tags
          git config --global user.email "antoniojosedonishung@gmail.com"
          git config --global user.name "Antonio Donis"

      - name: Changelog
        run: "npx standard-version --releaseCommitMessageFormat \"[ci skip] chore(release): %s\""

      - name: Push changes
        run: git push --follow-tags origin main

      - id: latest_version
        name: Latest version
        run: node version.js >> $GITHUB_OUTPUT

  release:
    needs:
      - versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Linux binary
        run: go build -v -o bin/tulip
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Windows binary
        run: go build -v -o bin/tulip.exe
        env:
          GOOS: windows
          GOARCH: amd64

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/tulip
            bin/tulip.exe
          tag_name: v${{needs.versioning.outputs.version}}
        #run: echo "v${{needs.versioning.outputs.version}}"

      - name: Docker image
        run: echo "v${{needs.versioning.outputs.version}}"